#!/bin/bash

set -e
set -x

ARGUMENT_LIST=(
  "thornlist"
)
# Read arguments using getopt (allows for long option, whereas getopts does not)
opts=$(getopt \
  --longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
  --name "$(basename "$0")" \
  --options "" \
  -- "$@"
)

eval set --$opts

while [[ $# -gt 0 ]]; do
  case "$1" in
    --thornlist)
      thornlist=$2
      shift 2
      ;;
    *)
      break
      ;;
  esac
done

. cactus/sim-functions.sh

simdir=$WORKSPACE/../simulations
mkdir -p $simdir

if [ -z "$USER" ]; then
export USER=jenkins
fi

# Arg exported by build-and-test.sh
# Simfactory assumes it is in master
cd $MASTER

host=$(hostname -f)

########################################################################################
# Configure SimFactory
########################################################################################

# Remove any simfactory configuration from previous runs
rm -f simfactory/etc/defs.local.ini
rm -f simfactory/mdb/machines/${host}.ini

simfactory/bin/sim setup-silent

machine=$(simfactory/bin/sim whoami|grep 'Current machine'|awk '{print $3}')
echo "machine = $machine"

cat <<EOF >simfactory/etc/filter.local.rules
- simulations/
EOF

simfactory/bin/sim whoami

machine=$(simfactory/bin/sim whoami|grep 'Current machine'|awk '{print $3}')

########################################################################################
# Build
########################################################################################

export CCACHE_DIR=$WORKSPACE/ccache
mkdir -p $CCACHE_DIR

# disable colours in error messages and warnings
export GCC_COLORS=

if [ ! "z${BUILD_TYPE}" = "zIncremental" ]; then
    rm -rf configs/sim
fi

runscript=$(mdbentry $machine runscript)
optionlist=$(mdbentry $machine optionlist)
submitscript=$(mdbentry $machine submitscript)

time simfactory/bin/sim build --mdbkey make 'make -j2' --thornlist $thornlist --runscript $runscript --optionlist $optionlist --submitscript $submitscript --reconfig
