#!/bin/bash

make UsersGuideHTML
make MaintGuideHTML
make ReferenceManualHTML
make ThornDocHTML
make ArrangementDocHTML
make AllDocHTML

make UsersGuide
make MaintGuide
make ReferenceManual
make ThornDoc
make ArrangementDoc
make AllDoc

cd doc                                                                              
tar cfz HTML.tar.gz HTML                                                            
