#!/bin/bash

# this is the contents of Jenkins' Build shell script to check out and update
Cactus

set -e

export ENABLED_THORNS="
  CactusElliptic/EllPETSc
  CactusUtils/TATPETSc
  ExternalLibraries/PETSc
"

rm -f build__*.log
# Work around bugs in Jenkins

if [ "$SYNC_SUBMODULES" = "true" ]; then
  git submodule sync
fi

git submodule update --init #--force
# undo any local changes (do not use --force above since it always touches
# files)
git submodule foreach git checkout -f

if [ "$CLEAN_CACTUS_JENKINS" = "true" -o ! -r $WORKSPACE/cactusjenkins ]; then
  rm -rf $WORKSPACE/cactusjenkins
  git clone https://ianhinder@bitbucket.org/ianhinder/cactusjenkins.git $WORKSPACE/cactusjenkins
fi
if [ -r $WORKSPACE/configs/sim ]; then
  ( cd $WORKSPACE; make sim-cleandeps )
fi
time $WORKSPACE/cactusjenkins/build-cactus manifest/einsteintoolkit.th
time $WORKSPACE/cactusjenkins/test-cactus all
# it takes ~1hr to build the docs
#time $WORKSPACE/cactusjenkins/build-cactus-doc

#cd $WORKSPACE/repos/carpet
#doxygen
