# This is a basic workflow to help you get started with Actions

name: docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # TODO: create custom docker image for this
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      # Runs a single command using the runners shell
      - name: build documentation
        run: |
          set -e -x
          sudo apt-get update
          for p in make ghostscript texlive-plain-generic texlive-latex-recommended texlive-latex-extra curl ; do
            sudo apt-get install $p
          done
          apt-get clean
          cd $GITHUB_WORKSPACE/einsteintoolkit
          make AllDocHTML
          make AllDocHTML # twice to get all references in LaTeX
          tar -czf doc/HTML.tar.gz doc/HTML
          
      - name: Archive HTML docs
        uses: actions/upload-artifact@v3
        with:
          name: HTML.tar.gz
          path: docs/HTML.tar.gz
          retention-days: 1
        
      - name: Trigger update of HTML docs
        run: curl -kL https://www.einsteintoolkit.org/update.php/?update
